import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";
import type { Flight } from "@/lib/flights/types";
import { hhmm, datePart, formatDuration } from "@/lib/utils/dates";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, color: "#0F172A", fontFamily: "Helvetica" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#0EA5E9",
    color: "#FFFFFF",
    padding: 16,
    borderRadius: 8,
  },
  brand: { fontSize: 22, fontFamily: "Helvetica-Bold" },
  eticket: { fontSize: 9, letterSpacing: 1 },
  topRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 20 },
  label: { color: "#64748B", fontSize: 8, textTransform: "uppercase", marginTop: 8 },
  ref: { fontSize: 20, fontFamily: "Helvetica-Bold", color: "#0369A1" },
  value: { fontSize: 12 },
  qr: { width: 90, height: 90 },
  segment: {
    marginTop: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  segMain: { fontSize: 13, fontFamily: "Helvetica-Bold" },
  segSub: { color: "#64748B", marginTop: 2 },
  fareRow: {
    marginTop: 18,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  total: { fontSize: 14, fontFamily: "Helvetica-Bold", color: "#0369A1" },
  fine: { marginTop: 24, fontSize: 7.5, color: "#94A3B8", lineHeight: 1.4 },
});

export interface TicketProps {
  bookingRef: string;
  passengerName: string;
  flight: Flight;
  qrDataUrl: string;
  total: string;
}

export function TicketDocument({ bookingRef, passengerName, flight, qrDataUrl, total }: TicketProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.brand}>TRAVU</Text>
          <Text style={styles.eticket}>E-TICKET / ITINERARY RECEIPT</Text>
        </View>

        <View style={styles.topRow}>
          <View>
            <Text style={styles.label}>Booking reference</Text>
            <Text style={styles.ref}>{bookingRef}</Text>
            <Text style={styles.label}>Passenger</Text>
            <Text style={styles.value}>{passengerName.toUpperCase()}</Text>
            <Text style={styles.label}>Cabin</Text>
            <Text style={styles.value}>{flight.cabin}</Text>
          </View>
          <Image style={styles.qr} src={qrDataUrl} />
        </View>

        {flight.segments.map((s, i) => (
          <View key={i} style={styles.segment}>
            <View>
              <Text style={styles.segMain}>
                {s.originIata} {hhmm(s.departIso)} → {s.destIata} {hhmm(s.arriveIso)}
              </Text>
              <Text style={styles.segSub}>
                {s.airlineName} {s.airlineIata}
                {s.flightNo} · {datePart(s.departIso)} · {formatDuration(s.durationMin)}
              </Text>
            </View>
          </View>
        ))}

        <View style={styles.fareRow}>
          <Text>Total paid</Text>
          <Text style={styles.total}>{total}</Text>
        </View>

        <Text style={styles.fine}>
          This document is a simulated e-ticket generated by TRAVU for demonstration purposes only
          and is not valid for travel. Carriage is subject to the conditions of contract and tariffs
          of the operating carrier. Please arrive at the airport at least 3 hours before
          international departure with a valid passport and any required visas. Baggage allowances
          vary by fare and carrier. TRAVU booking reference {bookingRef}.
        </Text>
      </Page>
    </Document>
  );
}
